CREATE TABLE MEASUREMENT(
  ID IDENTITY NOT NULL PRIMARY KEY,
  TIME TIMESTAMP,
  VALUE FLOAT,
  ENGINEER_UNIT VARCHAR(40),
  QUALITY VARCHAR(40))
AS SELECT * FROM CSVREAD('src\main\resources\db\nppData\core_temperature.csv','ID,TIME,VALUE,ENGINEER_UNIT,QUALITY','fieldSeparator=,','rowSeparator=;');
